export type Building = {
  id: string;
  slug: string;
  name: string;
  nameJa?: string;
  architectId: string;
  architectName: string;
  yearCompleted?: number | null;
  status?: "built" | "unbuilt" | "renovated";
  country: string;
  city: string;
  ward?: string;
  district?: string;
  address?: string;
  location: {
    lat: number;
    lng: number;
  };
  geoPointSource?: string;
  coverImageUrl?: string;
  gallery?: string[];
  buildingType?: string;
  style?: string;
  structure?: string;
  materials?: string[];
  floorsAboveGround?: number | null;
  floorsBelowGround?: number | null;
  siteAreaSqm?: number | null;
  floorAreaSqm?: number | null;
  description?: string;
  shortDescription?: string;
  historicalContext?: string;
  designHighlights?: string[];
  experienceTags?: string[];
  styleTags?: string[];
  visitTips?: string[];
  nearestStation?: string;
  officialWebsite?: string;
  googleMapsUrl?: string;
  published: boolean;
  featured: boolean;
  createdAt: string;
  updatedAt: string;
};
